### ISSUE TITLE
Open-source plan

### ISSUE THREAD

**Issue by memoryunreal** [Surrey-UPLab/Recognize-Any-Regions#1]
Amazing work! When could the training code be open-sourced? I'm eager to follow your work! Thanks!

**Comment by Zesheng666** [comment]
me too

**Comment by happy-hsy** [comment]
Thank you for your interest! We're excited to announce that the code is now available for release!

**Comment by memoryunreal** [comment]
> Thank you for your interest! We're excited to announce that the code is now available for release!

Thanks! I will close the issue.
