### ISSUE TITLE
关于训练脚本

### ISSUE THREAD

**Issue by chencn2020** [Surrey-UPLab/Recognize-Any-Regions#10]
你好，请问你们最近会公布训练脚本吗
我在研究train_net的代码时，好像没有发现从RegionSpot()方法中调用模型的部分

**Comment by happy-hsy** [comment]
We have already released all the scripts, including those for training and testing. Please refer to the instructions provided at [this link](https://github.com/Surrey-UPLab/Recognize-Any-Regions/blob/main/GETTING_STARTED.md).
