### ISSUE TITLE
v3det_train loading error

### ISSUE THREAD

**Issue by YH-2023** [Surrey-UPLab/Recognize-Any-Regions#15]
When I performed the second phase of training, loading v3det_train was stuck. After pausing the program, an error like this appeared: AssertionError: Attribute 'thing_classes' in the metadata of 'v3det_train' cannot be set to a different value! This is why?

**Comment by happy-hsy** [comment]
Apologies for the late reply. Could you please attach the specific log so we can further identify the problem?

**Comment by happy-hsy** [comment]
What kind of machine did you use? And did you try using only V3Det to test the training?

**Comment by happy-hsy** [comment]
We have successfully run on the V100 and A100 (40GB). So for your situation, my idea is that loading v3det takes up a lot of CPU memory. Hence, can you monitor the changes in your machine’s CPU usage when using v3det?

**Comment by happy-hsy** [comment]
That is so strange. Did you try other solution, like change num_workers in the dataloader?  How many GPU did you used by the way?

**Comment by happy-hsy** [comment]
I suggest that you change the number of num_works to reduce the CPU load

**Comment by happy-hsy** [comment]
Because V3Det has a vast number of categories, the dataset needs to iterate through each category to map the IDs in Detectron2. Consequently, this will take up a lot of CPU memory.

**Comment by happy-hsy** [comment]
That what i am saying, loading the V3Det take lots of CPU and then stuck. What is the CPU memory you used?

**Comment by happy-hsy** [comment]
Could you please contact me directly via WeChat, WhatsApp, or Slack? I would be happy to provide detailed assistance. My email is haosen.yang.6@gmail.com
