### ISSUE TITLE
How to download the checkpoints

### ISSUE THREAD

**Issue by ArsenLuca** [Surrey-UPLab/Recognize-Any-Regions#2]
It seems that the checkpoints are placed at the netdisk of the University of Surrey, where I could not ascess

**Comment by Maxlinn** [comment]
me too. i try to download the checkpoints but seems the sharepoint directory is exclusive to surreyac-my.sharepoint.com

**Comment by happy-hsy** [comment]
All links have been updated. Please try downloading once more.

**Comment by ArsenLuca** [comment]
> All links have been updated. Please try downloading once more.

still unacessable, maybe you have not shared the Access Authority to public

**Comment by ArsenLuca** [comment]
Could you please try Google Drive?

**Comment by happy-hsy** [comment]
> Could you please try Google Drive?

Checkpoints are available on Google Drive.
