### ISSUE TITLE
is it possible to support text as prompt？

### ISSUE THREAD

**Issue by hariag** [Surrey-UPLab/Recognize-Any-Regions#5]
I find point and bbox as prompt but no text, is it possible to support text as prompt？

**Comment by happy-hsy** [comment]
We will be releasing the demo for the text prompt in a few days. Please stay tuned for updates.

**Comment by CQUMASTER** [comment]
> We will be releasing the demo for the text prompt in a few days. Please stay tuned for updates.
Has the version of text prompt been uploaded?
