### ISSUE TITLE
How to get the annotation file of openimages 

### ISSUE THREAD

**Issue by clearxu** [Surrey-UPLab/Recognize-Any-Regions#7]
_PREDEFINED_SPLITS_OPENIMAGES = {
    "openimages_train": ("openimages/detection/", "re_openimages_v6_train_bbox_splitdir_int_ids.json"),
    "openimages_val": ("openimages/detection/", "re_openimages_v6_train_bbox_splitdir_int_ids.json"),
}

**Comment by happy-hsy** [comment]
Thank you for your interest in RegionSpot. We're pleased to announce that we will soon release the "re_openimages_v6_train_bbox_splitdir_int_ids.json" file. Please stay tuned for updates.
