### ISSUE TITLE
using different sam models

### ISSUE THREAD

**Issue by george66s** [Surrey-UPLab/Recognize-Any-Regions#8]
Thanks for the great work!

Have you done any experiment on different sam model such as same_vit_h_4b8939.pth? What would the result be? Any improvement?

Thanks
George

**Comment by happy-hsy** [comment]
Thank you for your interest in RegionSpot. We have recently conducted an ablation study about the SAM model size, but it has not been released yet. Attached are the conclusions from our study. We plan to update Arxiv shortly.

![RegionSpot Study Conclusion](https://github.com/Surrey-UPLab/Recognize-Any-Regions/assets/29943705/b388d657-9a2b-4464-bfb9-cfeb387e7268)

![Additional Data](https://github.com/Surrey-UPLab/Recognize-Any-Regions/assets/29943705/625848a8-dd6d-4e43-922b-3db3f0fbc249)
