### ISSUE TITLE
询问offline_token

### ISSUE THREAD

**Issue by inhaowu** [Surrey-UPLab/Recognize-Any-Regions#9]
在使用自己的数据集进行训练时，我发现需要一个offline_token：
#read pth
pth_file = os.path.join(self.mask_tokens_dir, os.path.join(dataset_name, str(image_id)+'.pth'))
offline_token = torch.load(pth_file)
请问是需要提前在SAM中得到每个物体的分割embeddings吗？

**Comment by happy-hsy** [comment]
Yes, we pre-extract the embedding of each object in the annotations during the training stage to save time.

**Comment by inhaowu** [comment]
> Yes, we pre-extract the embedding of each object in the annotations during the training stage to save time.

fine, thanks!

**Comment by inhaowu** [comment]
> Yes, we pre-extract the embedding of each object in the annotations during the training stage to save time.

请问有没有相关的提取embeddings的代码呢？

**Comment by Originlightwkp** [comment]
@inhaowu  how to use your own dataset? Thank you!

**Comment by happy-hsy** [comment]
> > Yes, we pre-extract the embedding of each object in the annotations during the training stage to save time.
> 
> 请问有没有相关的提取embeddings的代码呢？

The release of the token extractor code will happen later, but you can currently refer to the provided inference code for embedding extraction. This process is straightforward and involves simple inference steps.

**Comment by inhaowu** [comment]
> @inhaowu how to use your own dataset? Thank you!

按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。

**Comment by happy-hsy** [comment]
> > @inhaowu how to use your own dataset? Thank you!
> 
> 按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。
We typically save only the last checkpoint by default. However, you can save checkpoints from any iteration by setting cfg.SOLVER.CHECKPOINT_PERIOD.

**Comment by happy-hsy** [comment]
> > @inhaowu how to use your own dataset? Thank you!
> 
> 按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。

We typically save only the last checkpoint by default. However, you can save checkpoints from any iteration by setting cfg.SOLVER.CHECKPOINT_PERIOD.

**Comment by happy-hsy** [comment]
> 谢谢您的解答！请问可以边训练边测试吗？
> […](#)
> ------------------ 原始邮件 ------------------ From: Haosen Yang ***@***.***&gt; 发送时间: 12/18/2023, 17:02 To: Surrey-UPLab/Recognize-Any-Regions ***@***.***&gt; 抄送: Inhao_Wu ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9) @inhaowu how to use your own dataset? Thank you! 按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。 We typically save only the last checkpoint by default. However, you can save checkpoints from any iteration by setting cfg.SOLVER.CHECKPOINT_PERIOD. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

This codebase are not support this now.

**Comment by inhaowu** [comment]
那请问怎么保证能得到best.pth呢？





------------------ 原始邮件 ------------------
From: Haosen Yang ***@***.***&gt;
发送时间: 12/18/2023, 17:40
To: Surrey-UPLab/Recognize-Any-Regions ***@***.***&gt;
抄送: Inhao_Wu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9)





  
谢谢您的解答！请问可以边训练边测试吗？
 …
 ------------------ 原始邮件 ------------------ From: Haosen Yang @.&gt; 发送时间: 12/18/2023, 17:02 To: Surrey-UPLab/Recognize-Any-Regions @.&gt; 抄送: Inhao_Wu @.&gt;, Mention @.&gt; Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9) @inhaowu how to use your own dataset? Thank you! 按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。 We typically save only the last checkpoint by default. However, you can save checkpoints from any iteration by setting cfg.SOLVER.CHECKPOINT_PERIOD. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
This codebase are not support this now.

**Comment by happy-hsy** [comment]
> 那请问怎么保证能得到best.pth呢？
> […](#)
> ------------------ 原始邮件 ------------------ From: Haosen Yang ***@***.***&gt; 发送时间: 12/18/2023, 17:40 To: Surrey-UPLab/Recognize-Any-Regions ***@***.***&gt; 抄送: Inhao_Wu ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9) 谢谢您的解答！请问可以边训练边测试吗？ … ------------------ 原始邮件 ------------------ From: Haosen Yang @.&gt; 发送时间: 12/18/2023, 17:02 To: Surrey-UPLab/Recognize-Any-Regions @.&gt; 抄送: Inhao_Wu @.&gt;, Mention @.&gt; Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9) @inhaowu how to use your own dataset? Thank you! 按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。 We typically save only the last checkpoint by default. However, you can save checkpoints from any iteration by setting cfg.SOLVER.CHECKPOINT_PERIOD. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; This codebase are not support this now. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

We utilize the last checkpoint directly, without making a specific selection.

**Comment by inhaowu** [comment]
Fine, thanks for you kind response!





------------------ 原始邮件 ------------------
From: Haosen Yang ***@***.***&gt;
发送时间: 12/18/2023, 17:52
To: Surrey-UPLab/Recognize-Any-Regions ***@***.***&gt;
抄送: Inhao_Wu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9)





  
那请问怎么保证能得到best.pth呢？
 …
 ------------------ 原始邮件 ------------------ From: Haosen Yang @.&gt; 发送时间: 12/18/2023, 17:40 To: Surrey-UPLab/Recognize-Any-Regions @.&gt; 抄送: Inhao_Wu @.&gt;, Mention @.&gt; Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9) 谢谢您的解答！请问可以边训练边测试吗？ … ------------------ 原始邮件 ------------------ From: Haosen Yang @.&gt; 发送时间: 12/18/2023, 17:02 To: Surrey-UPLab/Recognize-Any-Regions @.&gt; 抄送: Inhao_Wu @.&gt;, Mention @.&gt; Subject: Re: [Surrey-UPLab/Recognize-Any-Regions] 询问offline_token (Issue #9) @inhaowu how to use your own dataset? Thank you! 按照它的要求改数据集，加入比如'mask_tokens'那些，需要用SAM离线得到。不过我训练的时候没看到有任何.pth文件保存下来，有点奇怪。 We typically save only the last checkpoint by default. However, you can save checkpoints from any iteration by setting cfg.SOLVER.CHECKPOINT_PERIOD. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; This codebase are not support this now. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt;
  
We utilize the last checkpoint directly, without making a specific selection.
